M48
; DRILL file {KiCad (5.99.0-9812-gfee3c41c40)} date 03/20/21 22:32:54
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-03-20T22:32:54-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-9812-gfee3c41c40)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,ComponentDrill,NonPlated,NPTH
T1C0.0197
; #@! TA.AperFunction,ComponentDrill,NonPlated,NPTH
T2C0.0866
%
G90
G05
T1
; not plated pad hole
X6.0246Y-4.782
X6.2844Y-4.782
X6.5701Y-4.782
X6.8299Y-4.782
T2
X5.985Y-3.805
X6.88Y-3.805
T0
M30
