M48
; DRILL file {KiCad (5.99.0-9812-gfee3c41c40)} date 03/23/21 13:38:24
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-03-23T13:38:24-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-9812-gfee3c41c40)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,ComponentDrill,NonPlated,NPTH
T1C0.0866
%
G90
G05
T1
; not plated pad hole
X5.3238Y-2.0086
X5.4764Y-2.6299
X6.6575Y-2.6299
X6.81Y-2.0086
T0
M30
